version: '2'
services:
  web:
    build:
      context: web
    ports:
      - 8001:8001
    restart: always
    volumes:
      - ./web:/usr/src/app

  api:
    build:
      context: api
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./api:/usr/src/app
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    tty: true


  motion:
    build:
      context: api/src/motion
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ./api/src/motion:/usr/src/app
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
